site_name: PySR
theme:
  name: material
  palette:
    # Light mode:
    - media: "(prefers-color-scheme: light)"
      scheme: pysr
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    

  features:
    - navigation.expand

  logo: assets/pysr_logo_reduced.svg
  icon:
    repo: fontawesome/brands/github-alt
  favicon: assets/favicon.png

nav:
  - index.md
  - options.md
  - operators.md
  - Examples:
    - examples.md
    - papers.md
  - Reference:
    - api.md
    - api-advanced.md
  - backend.md

extra:
  homepage: https://astroautomata.com/PySR

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_url: https://github.com/MilesCranmer/PySR

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          # paths: [pysr]
          options:
            # https://mkdocstrings.github.io/python/usage/#finding-modules
            docstring_style: numpy
            merge_init_into_class: True
            # docstring_options
            # separate_signature: True
            show_bases: false
            heading_level: 2

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: True
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true